puppet:
        build: puppetmaster/
        hostname: puppet

agent1:
        build: puppetslave/
        hostname: agent1 
        privileged: true
        links:
            - puppet:puppet

agent2: 
        build: puppetubu/
        hostname: agent2
        privileged: true
        links:
            - puppet:puppet

agent3:
        build: puppetfed/
        hostname: agent3
        privileged: true
        links:
            - puppet:puppet
